"""Mechanism audit of completed temporal viability-preflight checkpoints.

This script never trains or mutates a checkpoint.  It evaluates the exhaustive
64-pattern set, decomposes the frozen post-warmup objective by output window,
and distinguishes candidate two-hop path timing from arrivals generated by
actually observed hidden spikes.
"""

from __future__ import annotations

import csv
import json
from functools import partial
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from data.boolean_dataset import ExhaustiveFixedOperationQueryDataset
from data.encoding import encode_simultaneous_trial
from snn.model import SNNSimultaneousModel
from train.trainer import window_class_balanced_mean


BASE = Path(__file__).resolve().parents[1]
RUN_ROOT = BASE / "runs/exploratory/simultaneous_temporal_viability_preflight_v1"
OUT = BASE / "docs/generated/simultaneous_temporal_checkpoint_mechanism_audit_v1"
CONDITIONS = [
    "d0", "scalar", "fixed_matched", "fixed_full_support",
    "temporal_scaffold", "w_and_d",
]


def build_model(cfg: dict) -> SNNSimultaneousModel:
    model = SNNSimultaneousModel(
        n_queries=int(cfg["K"]),
        n_hidden=int(cfg["n_hidden"]),
        win_len=int(cfg["win_len"]),
        read_len=int(cfg["read_len"]),
        d_max=int(cfg["d_max"]),
        train_mode=cfg["train_mode"],
        fixed_delay_value=cfg.get("fixed_delay_value"),
        fixed_delay_distribution=cfg.get("fixed_delay_distribution"),
        fixed_delay_seed=int(cfg.get("fixed_delay_seed", cfg["seed"])),
        fixed_delay_low=float(cfg.get("fixed_delay_low", 0.0)),
        fixed_delay_high=cfg.get("fixed_delay_high"),
        shared_delay=bool(cfg.get("shared_delay", False)),
        delay_init_mode=cfg["delay_init_mode"],
        delay_init_raw=float(cfg["delay_init_raw"]),
        delay_init_std=float(cfg["delay_init_std"]),
        lif_tau_m=float(cfg["lif_tau_m"]),
        lif_threshold=float(cfg["lif_threshold"]),
        lif_reset=float(cfg["lif_reset"]),
        lif_refractory=int(cfg["lif_refractory"]),
        surrogate_beta=float(cfg["surrogate_beta"]),
        n_input_channels=int(cfg["n_input"]),
        readout_type=cfg["readout_type"],
        use_output_spikes=bool(cfg.get("use_output_spikes", False)),
        n_output_neurons=cfg.get("n_output_neurons"),
        lif_output_threshold=cfg.get("lif_output_threshold"),
        observation_mode=cfg["observation_mode"],
        opponent_output_mode=cfg.get("opponent_output_mode"),
        output_window_len=cfg.get("output_window_len"),
    )
    scaffold = cfg.get("input_hidden_delay_scaffold")
    if scaffold is not None:
        row_delays = torch.tensor(
            scaffold["per_input_channel_delays"], dtype=model.syn_ih.weight.dtype
        )
        model.syn_ih.fixed_delay_tensor = row_delays[:, None].expand(
            model.n_input, model.n_hidden
        ).clone()
    return model


def exhaustive_batch(cfg: dict, device: str) -> tuple[torch.Tensor, torch.Tensor]:
    loader = DataLoader(
        ExhaustiveFixedOperationQueryDataset(cfg["query_ops"]),
        batch_size=64,
        shuffle=False,
    )
    A, B, op_ids, labels = next(iter(loader))
    encode_fn = partial(
        encode_simultaneous_trial,
        encoding_mode=cfg["encoding_mode"],
        burst_n_spikes_on=cfg["burst_n_spikes_on"],
        burst_n_spikes_off=cfg["burst_n_spikes_off"],
        burst_phase_on=cfg["burst_phase_on"],
        burst_phase_off=cfg["burst_phase_off"],
        burst_jitter_ms=cfg["burst_jitter_ms"],
    )
    spikes = encode_fn(
        A.to(device), B.to(device),
        win_len=int(cfg["win_len"]), read_len=int(cfg["read_len"]),
        r_on=float(cfg["r_on"]), r_off=float(cfg["r_off"]),
        dt=float(cfg["dt"]), device=device,
        op_ids=op_ids.to(device), n_ops=int(cfg.get("n_ops", 0)),
    )
    return spikes, labels.to(device).float()


def tensor_grad_stats(model: torch.nn.Module) -> dict[str, float]:
    names = {
        "delay_ih": getattr(model.syn_ih, "delay_raw", None),
        "delay_ho": getattr(model.syn_ho, "delay_raw", None),
        "weight_ih": model.syn_ih.weight,
        "weight_ho": model.syn_ho.weight,
    }
    result = {}
    for name, parameter in names.items():
        grad = None if parameter is None else parameter.grad
        result[f"{name}_grad_norm"] = (
            float(grad.detach().norm().item()) if grad is not None else 0.0
        )
        result[f"{name}_grad_nonzero_fraction"] = (
            float((grad.detach().abs() > 1e-12).float().mean().item())
            if grad is not None and grad.numel() else 0.0
        )
        if name.startswith("delay_") and grad is not None and grad.numel():
            synapse = model.syn_ih if name == "delay_ih" else model.syn_ho
            if synapse.delay_param_type == "sigmoid":
                raw = parameter.detach()
                sigma = torch.sigmoid(raw)
                jacobian = float(synapse.d_max) * sigma * (1.0 - sigma)
            else:
                jacobian = torch.ones_like(parameter.detach())
            descent_shift = -grad.detach() * jacobian
            result[f"{name}_descent_effective_shift_mean"] = float(
                descent_shift.mean().item()
            )
            result[f"{name}_descent_increase_fraction"] = float(
                (descent_shift > 0).float().mean().item()
            )
        elif name.startswith("delay_"):
            result[f"{name}_descent_effective_shift_mean"] = 0.0
            result[f"{name}_descent_increase_fraction"] = 0.0
    return result


def window_gradient_rows(
    model: SNNSimultaneousModel,
    spike_input: torch.Tensor,
    labels: torch.Tensor,
    cfg: dict,
) -> list[dict]:
    rows = []
    aux_weight = float(cfg.get("output_membrane_aux_weight", 0.2))
    for q in range(int(cfg["K"])):
        for objective in ("spike", "membrane", "combined"):
            model.zero_grad(set_to_none=True)
            logits, info = model(spike_input)
            spike_per_sample = F.binary_cross_entropy_with_logits(
                logits[:, q], labels[:, q], reduction="none"
            )
            class_target = torch.stack([1.0 - labels[:, q], labels[:, q]], dim=-1)
            membrane_per_sample = F.binary_cross_entropy_with_logits(
                info["output_membrane_class_logits"][:, q, :],
                class_target, reduction="none"
            ).mean(dim=-1)
            if cfg.get("loss_reduction") == "window_class_balanced":
                one_window_labels = labels[:, q:q + 1]
                spike_loss = window_class_balanced_mean(
                    spike_per_sample[:, None], one_window_labels
                )
                membrane_loss = window_class_balanced_mean(
                    membrane_per_sample[:, None], one_window_labels
                )
            else:
                spike_loss = spike_per_sample.mean()
                membrane_loss = membrane_per_sample.mean()
            if objective == "spike":
                loss = spike_loss
            elif objective == "membrane":
                loss = membrane_loss
            else:
                loss = spike_loss + aux_weight * membrane_loss
            loss.backward()
            rows.append({
                "condition": cfg["name"], "window": q,
                "objective": objective, "loss": float(loss.detach().item()),
                **tensor_grad_stats(model),
            })
    return rows


def window_trace_rows(
    condition: str,
    info: dict,
    labels: torch.Tensor,
    cfg: dict,
) -> list[dict]:
    hidden = info["hidden_spike_train"].float()
    output = info["output_spike_train"].float()
    current = info["output_synaptic_current_train"].float()
    rows = []
    start = int(cfg["win_len"])
    width = int(cfg["output_window_len"])
    for q in range(int(cfg["K"])):
        lo, hi = start + q * width, start + (q + 1) * width
        h_count = hidden[:, lo:hi].sum(dim=(1, 2))
        o_count = output[:, lo:hi].sum(dim=(1, 2))
        abs_current = current[:, lo:hi].abs().sum(dim=(1, 2))
        signed_current = (
            current[:, lo:hi, 1] - current[:, lo:hi, 0]
        ).sum(dim=1)
        y = labels[:, q].detach().cpu()
        signed_cpu = signed_current.detach().cpu()
        rows.append({
            "condition": condition, "window": q, "start": lo, "end": hi,
            "hidden_spikes_mean": float(h_count.mean().item()),
            "hidden_activity_fraction": float((h_count > 0).float().mean().item()),
            "output_spikes_mean": float(o_count.mean().item()),
            "output_activity_fraction": float((o_count > 0).float().mean().item()),
            "output_abs_current_mean": float(abs_current.mean().item()),
            "output_current_support_fraction": float(
                (abs_current > 1e-12).float().mean().item()
            ),
            "signed_current_label1_mean": float(signed_cpu[y == 1].mean().item()),
            "signed_current_label0_mean": float(signed_cpu[y == 0].mean().item()),
            "signed_current_class_gap": float(
                signed_cpu[y == 1].mean().item() - signed_cpu[y == 0].mean().item()
            ),
        })
    return rows


def add_histogram(
    hist: np.ndarray, times: np.ndarray, mass: np.ndarray
) -> None:
    valid = np.isfinite(times) & np.isfinite(mass) & (mass > 0)
    idx = np.floor(times[valid]).astype(int)
    keep = (idx >= 0) & (idx < len(hist))
    np.add.at(hist, idx[keep], mass[valid][keep])


def arrival_distributions(
    model: SNNSimultaneousModel,
    spike_input: torch.Tensor,
    hidden_train: torch.Tensor,
    horizon: int = 72,
) -> tuple[np.ndarray, np.ndarray]:
    """Return candidate two-hop and realized hidden-to-output arrival mass."""
    d_ih = model.syn_ih.get_delays().detach().cpu().numpy()
    d_ho = model.syn_ho.get_delays().detach().cpu().numpy()
    w_ih = model.syn_ih.weight.detach().cpu().numpy()
    w_ho = model.syn_ho.weight.detach().cpu().numpy()
    inputs = spike_input.detach().cpu().numpy()
    hidden = hidden_train.detach().cpu().numpy()
    candidate = np.zeros(horizon, dtype=np.float64)
    realized = np.zeros(horizon, dtype=np.float64)

    # Candidate two-hop paths: encoded event -> hidden synapse -> output synapse.
    for b, t, i in np.argwhere(inputs > 0):
        times = t + 2.0 + d_ih[i, :, None] + d_ho
        mass = np.abs(w_ih[i, :, None] * w_ho)
        add_histogram(candidate, times.ravel(), mass.ravel())

    # Realized arrivals: an actually emitted hidden spike traverses syn_ho.
    for b, t, h in np.argwhere(hidden > 0):
        times = t + 1.0 + d_ho[h, :]
        mass = np.abs(w_ho[h, :])
        add_histogram(realized, times.ravel(), mass.ravel())

    if candidate.sum() > 0:
        candidate /= candidate.sum()
    if realized.sum() > 0:
        realized /= realized.sum()
    return candidate, realized


def delay_rows(condition: str, model: SNNSimultaneousModel) -> list[dict]:
    rows = []
    for layer, synapse in (("input_hidden", model.syn_ih),
                           ("hidden_output", model.syn_ho)):
        values = synapse.get_delays().detach().cpu().numpy().ravel()
        rows.append({
            "condition": condition, "layer": layer, "n": len(values),
            "min": float(values.min()), "p25": float(np.percentile(values, 25)),
            "median": float(np.median(values)),
            "p75": float(np.percentile(values, 75)), "max": float(values.max()),
            "fraction_ge_10": float(np.mean(values >= 10)),
            "fraction_ge_20": float(np.mean(values >= 20)),
            "fraction_ge_25": float(np.mean(values >= 25)),
        })
    return rows


def write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    gradient_rows, trace_rows, delays = [], [], []
    histograms = {}
    for condition in CONDITIONS:
        run = RUN_ROOT / f"{condition}_opponent_shared_windowed_seed0"
        cfg = json.loads((run / "config.json").read_text(encoding="utf-8"))
        model = build_model(cfg)
        state = torch.load(run / "last_model.pt", map_location="cpu", weights_only=True)
        model.load_state_dict(state)
        model.eval()
        spike_input, labels = exhaustive_batch(cfg, "cpu")
        gradient_rows.extend(window_gradient_rows(model, spike_input, labels, cfg))
        with torch.no_grad():
            _, info = model(spike_input, record=True)
        trace_rows.extend(window_trace_rows(condition, info, labels, cfg))
        delays.extend(delay_rows(condition, model))
        histograms[condition] = arrival_distributions(
            model, spike_input, info["hidden_spike_train"]
        )

    write_csv(OUT / "window_gradients.csv", gradient_rows)
    write_csv(OUT / "window_mechanisms.csv", trace_rows)
    write_csv(OUT / "delay_summary.csv", delays)

    arrival_rows = []
    for condition, (candidate, realized) in histograms.items():
        for t in range(len(candidate)):
            arrival_rows.append({
                "condition": condition, "time_bin": t,
                "candidate_two_hop_mass": float(candidate[t]),
                "realized_output_arrival_mass": float(realized[t]),
            })
    write_csv(OUT / "arrival_histograms.csv", arrival_rows)

    windows = [0, 1, 2]
    fig, axes = plt.subplots(2, 2, figsize=(13, 8))
    for condition in CONDITIONS:
        rows = [r for r in trace_rows if r["condition"] == condition]
        axes[0, 0].plot(windows, [r["hidden_activity_fraction"] for r in rows],
                        marker="o", label=condition)
        axes[0, 1].plot(windows, [r["output_current_support_fraction"] for r in rows],
                        marker="o", label=condition)
        axes[1, 0].plot(np.arange(len(histograms[condition][1])),
                        histograms[condition][1], label=condition)
    wad_grad = [r for r in gradient_rows
                if r["condition"] == "w_and_d" and r["objective"] == "combined"]
    axes[1, 1].plot(windows, [r["delay_ih_grad_norm"] for r in wad_grad],
                    marker="o", label="input-hidden")
    axes[1, 1].plot(windows, [r["delay_ho_grad_norm"] for r in wad_grad],
                    marker="o", label="hidden-output")
    axes[0, 0].set(title="Hidden emission support", xlabel="output window",
                   ylabel="trial fraction")
    axes[0, 1].set(title="Output synaptic-current support", xlabel="output window",
                   ylabel="trial fraction")
    axes[1, 0].set(title="Realized hidden-to-output arrival mass", xlabel="time bin",
                   ylabel="normalized |weight| mass", xlim=(0, 45))
    axes[1, 1].set(title="WAD window-specific combined-loss gradients",
                   xlabel="output window", ylabel="gradient norm", yscale="log")
    for ax in axes.ravel():
        ax.grid(alpha=.25)
        ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(OUT / "mechanism_audit.png", dpi=180)
    plt.close(fig)

    summary = {
        "protocol": "simultaneous_temporal_checkpoint_mechanism_audit_v1",
        "source_checkpoints": "simultaneous_temporal_viability_preflight_v1/final",
        "patterns": 64,
        "training_or_checkpoint_mutation": False,
        "window_mechanisms": trace_rows,
        "window_gradients": gradient_rows,
        "delay_summary": delays,
    }
    (OUT / "audit.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote mechanism audit to {OUT}")


if __name__ == "__main__":
    main()
